const CLUB_CRESTS: Record<string, string> = {
  'arsenal':           'https://crests.football-data.org/57.png',
  'aston villa':       'https://crests.football-data.org/58.png',
  'bournemouth':       'https://crests.football-data.org/1044.png',
  'brentford':         'https://crests.football-data.org/402.png',
  'brighton':          'https://crests.football-data.org/397.png',
  'brighton & hove albion': 'https://crests.football-data.org/397.png',
  'chelsea':           'https://crests.football-data.org/61.png',
  'crystal palace':    'https://crests.football-data.org/354.png',
  'everton':           'https://crests.football-data.org/62.png',
  'fulham':            'https://crests.football-data.org/63.png',
  'ipswich':           'https://crests.football-data.org/349.png',
  'ipswich town':      'https://crests.football-data.org/349.png',
  'leicester':         'https://crests.football-data.org/338.png',
  'leicester city':    'https://crests.football-data.org/338.png',
  'liverpool':         'https://crests.football-data.org/64.png',
  'man city':          'https://crests.football-data.org/65.png',
  'man united':        'https://crests.football-data.org/66.png',
  'man utd':           'https://crests.football-data.org/66.png',
  'manchester city':   'https://crests.football-data.org/65.png',
  'manchester united': 'https://crests.football-data.org/66.png',
  'manchester utd':    'https://crests.football-data.org/66.png',
  'newcastle':         'https://crests.football-data.org/67.png',
  'newcastle utd':     'https://crests.football-data.org/67.png',
  'newcastle united':  'https://crests.football-data.org/67.png',
  'nottm forest':      '/forest%20logo.png',
  "nott'ham forest":   '/forest%20logo.png',
  "nott'm forest":     '/forest%20logo.png',
  'nottingham forest': '/forest%20logo.png',
  'southampton':       'https://crests.football-data.org/340.png',
  'tottenham':         'https://crests.football-data.org/73.png',
  'tottenham hotspur': 'https://crests.football-data.org/73.png',
  'spurs':             'https://crests.football-data.org/73.png',
  'west ham':          'https://crests.football-data.org/563.png',
  'west ham united':   'https://crests.football-data.org/563.png',
  'wolves':            'https://crests.football-data.org/76.png',
  'wolverhampton':     'https://crests.football-data.org/76.png',
  'wolverhampton wanderers': 'https://crests.football-data.org/76.png',

  'leeds':          'https://crests.football-data.org/341.png',
  'sunderland':     'https://crests.football-data.org/69.png',
  'sheffield utd':  'https://crests.football-data.org/356.png',
  'middlesbrough':  'https://crests.football-data.org/343.png',

  'barcelona':      'https://crests.football-data.org/81.png',
  'real madrid':    'https://crests.football-data.org/86.png',
  'atletico madrid':'https://crests.football-data.org/78.png',
  'sevilla':        'https://crests.football-data.org/559.png',
  'valencia':       'https://crests.football-data.org/95.png',
  'villarreal':     'https://crests.football-data.org/94.png',
  'real sociedad':  'https://crests.football-data.org/92.png',
  'athletic bilbao':'https://crests.football-data.org/77.png',
  'girona':         'https://crests.football-data.org/298.png',
  'real betis':     'https://crests.football-data.org/90.png',

  'bayern munich':  'https://crests.football-data.org/5.png',
  'b. münchen':     'https://crests.football-data.org/5.png',
  'dortmund':       'https://crests.football-data.org/4.png',
  'borussia dortmund': 'https://crests.football-data.org/4.png',
  'b. dortmund':    'https://crests.football-data.org/4.png',
  'bayer leverkusen': 'https://crests.football-data.org/3.png',
  'b. leverkusen':  'https://crests.football-data.org/3.png',
  'leverkusen':     'https://crests.football-data.org/3.png',
  'rb leipzig':     'https://crests.football-data.org/721.png',
  'eintracht frankfurt': 'https://crests.football-data.org/19.png',
  'frankfurt':      'https://crests.football-data.org/19.png',
  'wolfsburg':      'https://crests.football-data.org/11.png',
  'freiburg':       'https://crests.football-data.org/17.png',
  'hoffenheim':     'https://crests.football-data.org/2.png',
  'monchengladbach': 'https://crests.football-data.org/18.png',

  'juventus':       'https://crests.football-data.org/109.png',
  'inter milan':    'https://crests.football-data.org/108.png',
  'inter':          'https://crests.football-data.org/108.png',
  'ac milan':       'https://crests.football-data.org/98.png',
  'milan':          'https://crests.football-data.org/98.png',
  'napoli':         'https://crests.football-data.org/113.png',
  'roma':           'https://crests.football-data.org/100.png',
  'as roma':        'https://crests.football-data.org/100.png',
  'lazio':          'https://crests.football-data.org/110.png',
  'atalanta':       'https://crests.football-data.org/102.png',
  'fiorentina':     'https://crests.football-data.org/99.png',

  'psg':            'https://crests.football-data.org/524.png',
  'paris saint-germain': 'https://crests.football-data.org/524.png',
  'marseille':      'https://crests.football-data.org/516.png',
  'lyon':           'https://crests.football-data.org/523.png',
  'monaco':         'https://crests.football-data.org/548.png',
  'lille':          'https://crests.football-data.org/521.png',
  'rennes':         'https://crests.football-data.org/529.png',
  'nice':           'https://crests.football-data.org/522.png',
  'lens':           'https://crests.football-data.org/532.png',
  'metz':           'https://crests.football-data.org/539.png',
  'strasbourg':     'https://crests.football-data.org/576.png',

  'ajax':           'https://crests.football-data.org/678.png',
  'psv':            'https://crests.football-data.org/674.png',
  'feyenoord':      'https://crests.football-data.org/675.png',
  'az alkmaar':     'https://crests.football-data.org/672.png',

  'benfica':        'https://crests.football-data.org/498.png',
  'porto':          'https://crests.football-data.org/503.png',
  'sporting cp':    'https://crests.football-data.org/498.png',
  'braga':          'https://crests.football-data.org/182.png',

  'celtic':         'https://crests.football-data.org/264.png',
  'rangers':        'https://crests.football-data.org/257.png',
  'anderlecht':     'https://crests.football-data.org/246.png',
};

export function getClubCrest(raw: string): string {
  if (!raw) return '';
  // Handle loan arrows: "Club A → Club B" → use last club
  const club = raw.includes('→') ? raw.split('→').pop()!.trim() : raw.trim();
  const key = club.toLowerCase().trim();
  return CLUB_CRESTS[key] ?? '';
}
