// AUTO-GENERATED from the official 2024/25 Premier League schedule (openfootball/football.json).
// Maps each fixture ("Home_Away", using the prediction-table team names) to its real matchweek
// and a display date. Drives the Match Predictions gameweek dropdown.

export const GW_MAP: Record<string, number> = {
  "Manchester United_Fulham": 1,
  "Ipswich_Liverpool": 1,
  "Arsenal_Wolves": 1,
  "Everton_Brighton": 1,
  "Newcastle_Southampton": 1,
  "Nott'm Forest_Bournemouth": 1,
  "West Ham_Aston Villa": 1,
  "Brentford_Crystal Palace": 1,
  "Chelsea_Manchester City": 1,
  "Leicester_Tottenham": 1,
  "Brighton_Manchester United": 2,
  "Crystal Palace_West Ham": 2,
  "Fulham_Leicester": 2,
  "Manchester City_Ipswich": 2,
  "Southampton_Nott'm Forest": 2,
  "Tottenham_Everton": 2,
  "Aston Villa_Arsenal": 2,
  "Bournemouth_Newcastle": 2,
  "Wolves_Chelsea": 2,
  "Liverpool_Brentford": 2,
  "Arsenal_Brighton": 3,
  "Brentford_Southampton": 3,
  "Everton_Bournemouth": 3,
  "Ipswich_Fulham": 3,
  "Leicester_Aston Villa": 3,
  "Nott'm Forest_Wolves": 3,
  "West Ham_Manchester City": 3,
  "Chelsea_Crystal Palace": 3,
  "Newcastle_Tottenham": 3,
  "Manchester United_Liverpool": 3,
  "Southampton_Manchester United": 4,
  "Brighton_Ipswich": 4,
  "Crystal Palace_Leicester": 4,
  "Fulham_West Ham": 4,
  "Liverpool_Nott'm Forest": 4,
  "Manchester City_Brentford": 4,
  "Aston Villa_Everton": 4,
  "Bournemouth_Chelsea": 4,
  "Tottenham_Arsenal": 4,
  "Wolves_Newcastle": 4,
  "West Ham_Chelsea": 5,
  "Aston Villa_Wolves": 5,
  "Fulham_Newcastle": 5,
  "Leicester_Everton": 5,
  "Liverpool_Bournemouth": 5,
  "Southampton_Ipswich": 5,
  "Tottenham_Brentford": 5,
  "Crystal Palace_Manchester United": 5,
  "Brighton_Nott'm Forest": 5,
  "Manchester City_Arsenal": 5,
  "Newcastle_Manchester City": 6,
  "Arsenal_Leicester": 6,
  "Brentford_West Ham": 6,
  "Chelsea_Brighton": 6,
  "Everton_Crystal Palace": 6,
  "Nott'm Forest_Fulham": 6,
  "Wolves_Liverpool": 6,
  "Ipswich_Aston Villa": 6,
  "Manchester United_Tottenham": 6,
  "Bournemouth_Southampton": 6,
  "Crystal Palace_Liverpool": 7,
  "Arsenal_Southampton": 7,
  "Brentford_Wolves": 7,
  "Leicester_Bournemouth": 7,
  "Manchester City_Fulham": 7,
  "West Ham_Ipswich": 7,
  "Everton_Newcastle": 7,
  "Aston Villa_Manchester United": 7,
  "Chelsea_Nott'm Forest": 7,
  "Brighton_Tottenham": 7,
  "Tottenham_West Ham": 8,
  "Fulham_Aston Villa": 8,
  "Ipswich_Everton": 8,
  "Manchester United_Brentford": 8,
  "Newcastle_Brighton": 8,
  "Southampton_Leicester": 8,
  "Bournemouth_Arsenal": 8,
  "Wolves_Manchester City": 8,
  "Liverpool_Chelsea": 8,
  "Nott'm Forest_Crystal Palace": 8,
  "Leicester_Nott'm Forest": 9,
  "Aston Villa_Bournemouth": 9,
  "Brentford_Ipswich": 9,
  "Brighton_Wolves": 9,
  "Manchester City_Southampton": 9,
  "Everton_Fulham": 9,
  "Chelsea_Newcastle": 9,
  "Crystal Palace_Tottenham": 9,
  "West Ham_Manchester United": 9,
  "Arsenal_Liverpool": 9,
  "Newcastle_Arsenal": 10,
  "Bournemouth_Manchester City": 10,
  "Ipswich_Leicester": 10,
  "Liverpool_Brighton": 10,
  "Nott'm Forest_West Ham": 10,
  "Southampton_Everton": 10,
  "Wolves_Crystal Palace": 10,
  "Tottenham_Aston Villa": 10,
  "Manchester United_Chelsea": 10,
  "Fulham_Brentford": 10,
  "Brentford_Bournemouth": 11,
  "Crystal Palace_Fulham": 11,
  "West Ham_Everton": 11,
  "Wolves_Southampton": 11,
  "Brighton_Manchester City": 11,
  "Liverpool_Aston Villa": 11,
  "Manchester United_Leicester": 11,
  "Nott'm Forest_Newcastle": 11,
  "Tottenham_Ipswich": 11,
  "Chelsea_Arsenal": 11,
  "Leicester_Chelsea": 12,
  "Bournemouth_Brighton": 12,
  "Arsenal_Nott'm Forest": 12,
  "Aston Villa_Crystal Palace": 12,
  "Everton_Brentford": 12,
  "Fulham_Wolves": 12,
  "Manchester City_Tottenham": 12,
  "Southampton_Liverpool": 12,
  "Ipswich_Manchester United": 12,
  "Newcastle_West Ham": 12,
  "Brighton_Southampton": 13,
  "Brentford_Leicester": 13,
  "Crystal Palace_Newcastle": 13,
  "Nott'm Forest_Ipswich": 13,
  "Wolves_Bournemouth": 13,
  "West Ham_Arsenal": 13,
  "Chelsea_Aston Villa": 13,
  "Manchester United_Everton": 13,
  "Tottenham_Fulham": 13,
  "Liverpool_Manchester City": 13,
  "Ipswich_Crystal Palace": 14,
  "Leicester_West Ham": 14,
  "Everton_Wolves": 14,
  "Manchester City_Nott'm Forest": 14,
  "Newcastle_Liverpool": 14,
  "Southampton_Chelsea": 14,
  "Arsenal_Manchester United": 14,
  "Aston Villa_Brentford": 14,
  "Fulham_Brighton": 14,
  "Bournemouth_Tottenham": 14,
  "Aston Villa_Southampton": 15,
  "Brentford_Newcastle": 15,
  "Crystal Palace_Manchester City": 15,
  "Manchester United_Nott'm Forest": 15,
  "Fulham_Arsenal": 15,
  "Ipswich_Bournemouth": 15,
  "Leicester_Brighton": 15,
  "Tottenham_Chelsea": 15,
  "West Ham_Wolves": 15,
  "Arsenal_Everton": 16,
  "Liverpool_Fulham": 16,
  "Newcastle_Leicester": 16,
  "Wolves_Ipswich": 16,
  "Nott'm Forest_Aston Villa": 16,
  "Brighton_Crystal Palace": 16,
  "Manchester City_Manchester United": 16,
  "Chelsea_Brentford": 16,
  "Southampton_Tottenham": 16,
  "Bournemouth_West Ham": 16,
  "Aston Villa_Manchester City": 17,
  "Brentford_Nott'm Forest": 17,
  "Ipswich_Newcastle": 17,
  "West Ham_Brighton": 17,
  "Crystal Palace_Arsenal": 17,
  "Everton_Chelsea": 17,
  "Fulham_Southampton": 17,
  "Leicester_Wolves": 17,
  "Manchester United_Bournemouth": 17,
  "Tottenham_Liverpool": 17,
  "Manchester City_Everton": 18,
  "Bournemouth_Crystal Palace": 18,
  "Chelsea_Fulham": 18,
  "Newcastle_Aston Villa": 18,
  "Nott'm Forest_Tottenham": 18,
  "Southampton_West Ham": 18,
  "Wolves_Manchester United": 18,
  "Liverpool_Leicester": 18,
  "Brighton_Brentford": 18,
  "Arsenal_Ipswich": 18,
  "Leicester_Manchester City": 19,
  "Crystal Palace_Southampton": 19,
  "Everton_Nott'm Forest": 19,
  "Fulham_Bournemouth": 19,
  "Tottenham_Wolves": 19,
  "West Ham_Liverpool": 19,
  "Aston Villa_Brighton": 19,
  "Ipswich_Chelsea": 19,
  "Manchester United_Newcastle": 19,
  "Brentford_Arsenal": 19,
  "Tottenham_Newcastle": 20,
  "Southampton_Brentford": 20,
  "Crystal Palace_Chelsea": 20,
  "Bournemouth_Everton": 20,
  "Aston Villa_Leicester": 20,
  "Manchester City_West Ham": 20,
  "Brighton_Arsenal": 20,
  "Fulham_Ipswich": 20,
  "Liverpool_Manchester United": 20,
  "Wolves_Nott'm Forest": 20,
  "West Ham_Fulham": 21,
  "Brentford_Manchester City": 21,
  "Chelsea_Bournemouth": 21,
  "Nott'm Forest_Liverpool": 21,
  "Everton_Aston Villa": 21,
  "Leicester_Crystal Palace": 21,
  "Newcastle_Wolves": 21,
  "Arsenal_Tottenham": 21,
  "Ipswich_Brighton": 21,
  "Manchester United_Southampton": 21,
  "Newcastle_Bournemouth": 22,
  "West Ham_Crystal Palace": 22,
  "Leicester_Fulham": 22,
  "Brentford_Liverpool": 22,
  "Arsenal_Aston Villa": 22,
  "Manchester United_Brighton": 22,
  "Nott'm Forest_Southampton": 22,
  "Everton_Tottenham": 22,
  "Ipswich_Manchester City": 22,
  "Chelsea_Wolves": 22,
  "Liverpool_Ipswich": 23,
  "Wolves_Arsenal": 23,
  "Brighton_Everton": 23,
  "Southampton_Newcastle": 23,
  "Bournemouth_Nott'm Forest": 23,
  "Manchester City_Chelsea": 23,
  "Crystal Palace_Brentford": 23,
  "Tottenham_Leicester": 23,
  "Aston Villa_West Ham": 23,
  "Fulham_Manchester United": 23,
  "Nott'm Forest_Brighton": 24,
  "Newcastle_Fulham": 24,
  "Everton_Leicester": 24,
  "Bournemouth_Liverpool": 24,
  "Ipswich_Southampton": 24,
  "Wolves_Aston Villa": 24,
  "Manchester United_Crystal Palace": 24,
  "Brentford_Tottenham": 24,
  "Arsenal_Manchester City": 24,
  "Chelsea_West Ham": 24,
  "Everton_Liverpool": 15,
  "Brighton_Chelsea": 25,
  "Leicester_Arsenal": 25,
  "Southampton_Bournemouth": 25,
  "West Ham_Brentford": 25,
  "Aston Villa_Ipswich": 25,
  "Manchester City_Newcastle": 25,
  "Fulham_Nott'm Forest": 25,
  "Crystal Palace_Everton": 25,
  "Liverpool_Wolves": 25,
  "Tottenham_Manchester United": 25,
  "Aston Villa_Liverpool": 29,
  "Leicester_Brentford": 26,
  "Everton_Manchester United": 26,
  "Ipswich_Tottenham": 26,
  "Fulham_Crystal Palace": 26,
  "Arsenal_West Ham": 26,
  "Bournemouth_Wolves": 26,
  "Southampton_Brighton": 26,
  "Aston Villa_Chelsea": 26,
  "Newcastle_Nott'm Forest": 26,
  "Manchester City_Liverpool": 26,
  "Brighton_Bournemouth": 27,
  "Crystal Palace_Aston Villa": 27,
  "Wolves_Fulham": 27,
  "Chelsea_Southampton": 27,
  "Nott'm Forest_Arsenal": 27,
  "Brentford_Everton": 27,
  "Tottenham_Manchester City": 27,
  "Manchester United_Ipswich": 27,
  "Liverpool_Newcastle": 27,
  "West Ham_Leicester": 27,
  "Nott'm Forest_Manchester City": 28,
  "Brighton_Fulham": 28,
  "Crystal Palace_Ipswich": 28,
  "Liverpool_Southampton": 28,
  "Brentford_Aston Villa": 28,
  "Wolves_Everton": 28,
  "Tottenham_Bournemouth": 28,
  "Chelsea_Leicester": 28,
  "Manchester United_Arsenal": 28,
  "West Ham_Newcastle": 28,
  "Everton_West Ham": 29,
  "Ipswich_Nott'm Forest": 29,
  "Manchester City_Brighton": 29,
  "Southampton_Wolves": 29,
  "Bournemouth_Brentford": 29,
  "Arsenal_Chelsea": 29,
  "Fulham_Tottenham": 29,
  "Leicester_Manchester United": 29,
  "Arsenal_Fulham": 30,
  "Wolves_West Ham": 30,
  "Nott'm Forest_Manchester United": 30,
  "Bournemouth_Ipswich": 30,
  "Brighton_Aston Villa": 30,
  "Manchester City_Leicester": 30,
  "Newcastle_Brentford": 30,
  "Southampton_Crystal Palace": 30,
  "Liverpool_Everton": 30,
  "Chelsea_Tottenham": 30,
  "Everton_Arsenal": 31,
  "Crystal Palace_Brighton": 31,
  "Ipswich_Wolves": 31,
  "West Ham_Bournemouth": 31,
  "Aston Villa_Nott'm Forest": 31,
  "Brentford_Chelsea": 31,
  "Fulham_Liverpool": 31,
  "Tottenham_Southampton": 31,
  "Manchester United_Manchester City": 31,
  "Leicester_Newcastle": 31,
  "Manchester City_Crystal Palace": 32,
  "Brighton_Leicester": 32,
  "Nott'm Forest_Everton": 32,
  "Southampton_Aston Villa": 32,
  "Arsenal_Brentford": 32,
  "Chelsea_Ipswich": 32,
  "Liverpool_West Ham": 32,
  "Wolves_Tottenham": 32,
  "Newcastle_Manchester United": 32,
  "Bournemouth_Fulham": 32,
  "Newcastle_Crystal Palace": 29,
  "Brentford_Brighton": 33,
  "Crystal Palace_Bournemouth": 33,
  "Everton_Manchester City": 33,
  "West Ham_Southampton": 33,
  "Aston Villa_Newcastle": 33,
  "Fulham_Chelsea": 33,
  "Ipswich_Arsenal": 33,
  "Manchester United_Wolves": 33,
  "Leicester_Liverpool": 33,
  "Tottenham_Nott'm Forest": 33,
  "Manchester City_Aston Villa": 34,
  "Arsenal_Crystal Palace": 34,
  "Chelsea_Everton": 34,
  "Brighton_West Ham": 34,
  "Newcastle_Ipswich": 34,
  "Southampton_Fulham": 34,
  "Wolves_Leicester": 34,
  "Bournemouth_Manchester United": 34,
  "Liverpool_Tottenham": 34,
  "Nott'm Forest_Brentford": 34,
  "Manchester City_Wolves": 35,
  "Aston Villa_Fulham": 35,
  "Everton_Ipswich": 35,
  "Leicester_Southampton": 35,
  "Arsenal_Bournemouth": 35,
  "Brentford_Manchester United": 35,
  "Brighton_Newcastle": 35,
  "West Ham_Tottenham": 35,
  "Chelsea_Liverpool": 35,
  "Crystal Palace_Nott'm Forest": 35,
  "Fulham_Everton": 36,
  "Ipswich_Brentford": 36,
  "Southampton_Manchester City": 36,
  "Wolves_Brighton": 36,
  "Bournemouth_Aston Villa": 36,
  "Newcastle_Chelsea": 36,
  "Manchester United_West Ham": 36,
  "Nott'm Forest_Leicester": 36,
  "Tottenham_Crystal Palace": 36,
  "Liverpool_Arsenal": 36,
  "Aston Villa_Tottenham": 37,
  "Chelsea_Manchester United": 37,
  "Everton_Southampton": 37,
  "West Ham_Nott'm Forest": 37,
  "Brentford_Fulham": 37,
  "Leicester_Ipswich": 37,
  "Arsenal_Newcastle": 37,
  "Brighton_Liverpool": 37,
  "Crystal Palace_Wolves": 37,
  "Manchester City_Bournemouth": 37,
  "Bournemouth_Leicester": 38,
  "Fulham_Manchester City": 38,
  "Ipswich_West Ham": 38,
  "Liverpool_Crystal Palace": 38,
  "Manchester United_Aston Villa": 38,
  "Newcastle_Everton": 38,
  "Nott'm Forest_Chelsea": 38,
  "Southampton_Arsenal": 38,
  "Tottenham_Brighton": 38,
  "Wolves_Brentford": 38,
};

export const GW_DATE: Record<string, string> = {
  "Manchester United_Fulham": "Fri 16 Aug 2024",
  "Ipswich_Liverpool": "Sat 17 Aug 2024",
  "Arsenal_Wolves": "Sat 17 Aug 2024",
  "Everton_Brighton": "Sat 17 Aug 2024",
  "Newcastle_Southampton": "Sat 17 Aug 2024",
  "Nott'm Forest_Bournemouth": "Sat 17 Aug 2024",
  "West Ham_Aston Villa": "Sat 17 Aug 2024",
  "Brentford_Crystal Palace": "Sun 18 Aug 2024",
  "Chelsea_Manchester City": "Sun 18 Aug 2024",
  "Leicester_Tottenham": "Mon 19 Aug 2024",
  "Brighton_Manchester United": "Sat 24 Aug 2024",
  "Crystal Palace_West Ham": "Sat 24 Aug 2024",
  "Fulham_Leicester": "Sat 24 Aug 2024",
  "Manchester City_Ipswich": "Sat 24 Aug 2024",
  "Southampton_Nott'm Forest": "Sat 24 Aug 2024",
  "Tottenham_Everton": "Sat 24 Aug 2024",
  "Aston Villa_Arsenal": "Sat 24 Aug 2024",
  "Bournemouth_Newcastle": "Sun 25 Aug 2024",
  "Wolves_Chelsea": "Sun 25 Aug 2024",
  "Liverpool_Brentford": "Sun 25 Aug 2024",
  "Arsenal_Brighton": "Sat 31 Aug 2024",
  "Brentford_Southampton": "Sat 31 Aug 2024",
  "Everton_Bournemouth": "Sat 31 Aug 2024",
  "Ipswich_Fulham": "Sat 31 Aug 2024",
  "Leicester_Aston Villa": "Sat 31 Aug 2024",
  "Nott'm Forest_Wolves": "Sat 31 Aug 2024",
  "West Ham_Manchester City": "Sat 31 Aug 2024",
  "Chelsea_Crystal Palace": "Sun 1 Sep 2024",
  "Newcastle_Tottenham": "Sun 1 Sep 2024",
  "Manchester United_Liverpool": "Sun 1 Sep 2024",
  "Southampton_Manchester United": "Sat 14 Sep 2024",
  "Brighton_Ipswich": "Sat 14 Sep 2024",
  "Crystal Palace_Leicester": "Sat 14 Sep 2024",
  "Fulham_West Ham": "Sat 14 Sep 2024",
  "Liverpool_Nott'm Forest": "Sat 14 Sep 2024",
  "Manchester City_Brentford": "Sat 14 Sep 2024",
  "Aston Villa_Everton": "Sat 14 Sep 2024",
  "Bournemouth_Chelsea": "Sat 14 Sep 2024",
  "Tottenham_Arsenal": "Sun 15 Sep 2024",
  "Wolves_Newcastle": "Sun 15 Sep 2024",
  "West Ham_Chelsea": "Sat 21 Sep 2024",
  "Aston Villa_Wolves": "Sat 21 Sep 2024",
  "Fulham_Newcastle": "Sat 21 Sep 2024",
  "Leicester_Everton": "Sat 21 Sep 2024",
  "Liverpool_Bournemouth": "Sat 21 Sep 2024",
  "Southampton_Ipswich": "Sat 21 Sep 2024",
  "Tottenham_Brentford": "Sat 21 Sep 2024",
  "Crystal Palace_Manchester United": "Sat 21 Sep 2024",
  "Brighton_Nott'm Forest": "Sun 22 Sep 2024",
  "Manchester City_Arsenal": "Sun 22 Sep 2024",
  "Newcastle_Manchester City": "Sat 28 Sep 2024",
  "Arsenal_Leicester": "Sat 28 Sep 2024",
  "Brentford_West Ham": "Sat 28 Sep 2024",
  "Chelsea_Brighton": "Sat 28 Sep 2024",
  "Everton_Crystal Palace": "Sat 28 Sep 2024",
  "Nott'm Forest_Fulham": "Sat 28 Sep 2024",
  "Wolves_Liverpool": "Sat 28 Sep 2024",
  "Ipswich_Aston Villa": "Sun 29 Sep 2024",
  "Manchester United_Tottenham": "Sun 29 Sep 2024",
  "Bournemouth_Southampton": "Mon 30 Sep 2024",
  "Crystal Palace_Liverpool": "Sat 5 Oct 2024",
  "Arsenal_Southampton": "Sat 5 Oct 2024",
  "Brentford_Wolves": "Sat 5 Oct 2024",
  "Leicester_Bournemouth": "Sat 5 Oct 2024",
  "Manchester City_Fulham": "Sat 5 Oct 2024",
  "West Ham_Ipswich": "Sat 5 Oct 2024",
  "Everton_Newcastle": "Sat 5 Oct 2024",
  "Aston Villa_Manchester United": "Sun 6 Oct 2024",
  "Chelsea_Nott'm Forest": "Sun 6 Oct 2024",
  "Brighton_Tottenham": "Sun 6 Oct 2024",
  "Tottenham_West Ham": "Sat 19 Oct 2024",
  "Fulham_Aston Villa": "Sat 19 Oct 2024",
  "Ipswich_Everton": "Sat 19 Oct 2024",
  "Manchester United_Brentford": "Sat 19 Oct 2024",
  "Newcastle_Brighton": "Sat 19 Oct 2024",
  "Southampton_Leicester": "Sat 19 Oct 2024",
  "Bournemouth_Arsenal": "Sat 19 Oct 2024",
  "Wolves_Manchester City": "Sun 20 Oct 2024",
  "Liverpool_Chelsea": "Sun 20 Oct 2024",
  "Nott'm Forest_Crystal Palace": "Mon 21 Oct 2024",
  "Leicester_Nott'm Forest": "Fri 25 Oct 2024",
  "Aston Villa_Bournemouth": "Sat 26 Oct 2024",
  "Brentford_Ipswich": "Sat 26 Oct 2024",
  "Brighton_Wolves": "Sat 26 Oct 2024",
  "Manchester City_Southampton": "Sat 26 Oct 2024",
  "Everton_Fulham": "Sat 26 Oct 2024",
  "Chelsea_Newcastle": "Sun 27 Oct 2024",
  "Crystal Palace_Tottenham": "Sun 27 Oct 2024",
  "West Ham_Manchester United": "Sun 27 Oct 2024",
  "Arsenal_Liverpool": "Sun 27 Oct 2024",
  "Newcastle_Arsenal": "Sat 2 Nov 2024",
  "Bournemouth_Manchester City": "Sat 2 Nov 2024",
  "Ipswich_Leicester": "Sat 2 Nov 2024",
  "Liverpool_Brighton": "Sat 2 Nov 2024",
  "Nott'm Forest_West Ham": "Sat 2 Nov 2024",
  "Southampton_Everton": "Sat 2 Nov 2024",
  "Wolves_Crystal Palace": "Sat 2 Nov 2024",
  "Tottenham_Aston Villa": "Sun 3 Nov 2024",
  "Manchester United_Chelsea": "Sun 3 Nov 2024",
  "Fulham_Brentford": "Mon 4 Nov 2024",
  "Brentford_Bournemouth": "Sat 9 Nov 2024",
  "Crystal Palace_Fulham": "Sat 9 Nov 2024",
  "West Ham_Everton": "Sat 9 Nov 2024",
  "Wolves_Southampton": "Sat 9 Nov 2024",
  "Brighton_Manchester City": "Sat 9 Nov 2024",
  "Liverpool_Aston Villa": "Sat 9 Nov 2024",
  "Manchester United_Leicester": "Sun 10 Nov 2024",
  "Nott'm Forest_Newcastle": "Sun 10 Nov 2024",
  "Tottenham_Ipswich": "Sun 10 Nov 2024",
  "Chelsea_Arsenal": "Sun 10 Nov 2024",
  "Leicester_Chelsea": "Sat 23 Nov 2024",
  "Bournemouth_Brighton": "Sat 23 Nov 2024",
  "Arsenal_Nott'm Forest": "Sat 23 Nov 2024",
  "Aston Villa_Crystal Palace": "Sat 23 Nov 2024",
  "Everton_Brentford": "Sat 23 Nov 2024",
  "Fulham_Wolves": "Sat 23 Nov 2024",
  "Manchester City_Tottenham": "Sat 23 Nov 2024",
  "Southampton_Liverpool": "Sun 24 Nov 2024",
  "Ipswich_Manchester United": "Sun 24 Nov 2024",
  "Newcastle_West Ham": "Mon 25 Nov 2024",
  "Brighton_Southampton": "Fri 29 Nov 2024",
  "Brentford_Leicester": "Sat 30 Nov 2024",
  "Crystal Palace_Newcastle": "Sat 30 Nov 2024",
  "Nott'm Forest_Ipswich": "Sat 30 Nov 2024",
  "Wolves_Bournemouth": "Sat 30 Nov 2024",
  "West Ham_Arsenal": "Sat 30 Nov 2024",
  "Chelsea_Aston Villa": "Sun 1 Dec 2024",
  "Manchester United_Everton": "Sun 1 Dec 2024",
  "Tottenham_Fulham": "Sun 1 Dec 2024",
  "Liverpool_Manchester City": "Sun 1 Dec 2024",
  "Ipswich_Crystal Palace": "Tue 3 Dec 2024",
  "Leicester_West Ham": "Tue 3 Dec 2024",
  "Everton_Wolves": "Wed 4 Dec 2024",
  "Manchester City_Nott'm Forest": "Wed 4 Dec 2024",
  "Newcastle_Liverpool": "Wed 4 Dec 2024",
  "Southampton_Chelsea": "Wed 4 Dec 2024",
  "Arsenal_Manchester United": "Wed 4 Dec 2024",
  "Aston Villa_Brentford": "Wed 4 Dec 2024",
  "Fulham_Brighton": "Thu 5 Dec 2024",
  "Bournemouth_Tottenham": "Thu 5 Dec 2024",
  "Aston Villa_Southampton": "Sat 7 Dec 2024",
  "Brentford_Newcastle": "Sat 7 Dec 2024",
  "Crystal Palace_Manchester City": "Sat 7 Dec 2024",
  "Manchester United_Nott'm Forest": "Sat 7 Dec 2024",
  "Fulham_Arsenal": "Sun 8 Dec 2024",
  "Ipswich_Bournemouth": "Sun 8 Dec 2024",
  "Leicester_Brighton": "Sun 8 Dec 2024",
  "Tottenham_Chelsea": "Sun 8 Dec 2024",
  "West Ham_Wolves": "Mon 9 Dec 2024",
  "Arsenal_Everton": "Sat 14 Dec 2024",
  "Liverpool_Fulham": "Sat 14 Dec 2024",
  "Newcastle_Leicester": "Sat 14 Dec 2024",
  "Wolves_Ipswich": "Sat 14 Dec 2024",
  "Nott'm Forest_Aston Villa": "Sat 14 Dec 2024",
  "Brighton_Crystal Palace": "Sun 15 Dec 2024",
  "Manchester City_Manchester United": "Sun 15 Dec 2024",
  "Chelsea_Brentford": "Sun 15 Dec 2024",
  "Southampton_Tottenham": "Sun 15 Dec 2024",
  "Bournemouth_West Ham": "Mon 16 Dec 2024",
  "Aston Villa_Manchester City": "Sat 21 Dec 2024",
  "Brentford_Nott'm Forest": "Sat 21 Dec 2024",
  "Ipswich_Newcastle": "Sat 21 Dec 2024",
  "West Ham_Brighton": "Sat 21 Dec 2024",
  "Crystal Palace_Arsenal": "Sat 21 Dec 2024",
  "Everton_Chelsea": "Sun 22 Dec 2024",
  "Fulham_Southampton": "Sun 22 Dec 2024",
  "Leicester_Wolves": "Sun 22 Dec 2024",
  "Manchester United_Bournemouth": "Sun 22 Dec 2024",
  "Tottenham_Liverpool": "Sun 22 Dec 2024",
  "Manchester City_Everton": "Thu 26 Dec 2024",
  "Bournemouth_Crystal Palace": "Thu 26 Dec 2024",
  "Chelsea_Fulham": "Thu 26 Dec 2024",
  "Newcastle_Aston Villa": "Thu 26 Dec 2024",
  "Nott'm Forest_Tottenham": "Thu 26 Dec 2024",
  "Southampton_West Ham": "Thu 26 Dec 2024",
  "Wolves_Manchester United": "Thu 26 Dec 2024",
  "Liverpool_Leicester": "Thu 26 Dec 2024",
  "Brighton_Brentford": "Fri 27 Dec 2024",
  "Arsenal_Ipswich": "Fri 27 Dec 2024",
  "Leicester_Manchester City": "Sun 29 Dec 2024",
  "Crystal Palace_Southampton": "Sun 29 Dec 2024",
  "Everton_Nott'm Forest": "Sun 29 Dec 2024",
  "Fulham_Bournemouth": "Sun 29 Dec 2024",
  "Tottenham_Wolves": "Sun 29 Dec 2024",
  "West Ham_Liverpool": "Sun 29 Dec 2024",
  "Aston Villa_Brighton": "Mon 30 Dec 2024",
  "Ipswich_Chelsea": "Mon 30 Dec 2024",
  "Manchester United_Newcastle": "Mon 30 Dec 2024",
  "Brentford_Arsenal": "Wed 1 Jan 2025",
  "Tottenham_Newcastle": "Sat 4 Jan 2025",
  "Southampton_Brentford": "Sat 4 Jan 2025",
  "Crystal Palace_Chelsea": "Sat 4 Jan 2025",
  "Bournemouth_Everton": "Sat 4 Jan 2025",
  "Aston Villa_Leicester": "Sat 4 Jan 2025",
  "Manchester City_West Ham": "Sat 4 Jan 2025",
  "Brighton_Arsenal": "Sat 4 Jan 2025",
  "Fulham_Ipswich": "Sun 5 Jan 2025",
  "Liverpool_Manchester United": "Sun 5 Jan 2025",
  "Wolves_Nott'm Forest": "Mon 6 Jan 2025",
  "West Ham_Fulham": "Tue 14 Jan 2025",
  "Brentford_Manchester City": "Tue 14 Jan 2025",
  "Chelsea_Bournemouth": "Tue 14 Jan 2025",
  "Nott'm Forest_Liverpool": "Tue 14 Jan 2025",
  "Everton_Aston Villa": "Wed 15 Jan 2025",
  "Leicester_Crystal Palace": "Wed 15 Jan 2025",
  "Newcastle_Wolves": "Wed 15 Jan 2025",
  "Arsenal_Tottenham": "Wed 15 Jan 2025",
  "Ipswich_Brighton": "Thu 16 Jan 2025",
  "Manchester United_Southampton": "Thu 16 Jan 2025",
  "Newcastle_Bournemouth": "Sat 18 Jan 2025",
  "West Ham_Crystal Palace": "Sat 18 Jan 2025",
  "Leicester_Fulham": "Sat 18 Jan 2025",
  "Brentford_Liverpool": "Sat 18 Jan 2025",
  "Arsenal_Aston Villa": "Sat 18 Jan 2025",
  "Manchester United_Brighton": "Sun 19 Jan 2025",
  "Nott'm Forest_Southampton": "Sun 19 Jan 2025",
  "Everton_Tottenham": "Sun 19 Jan 2025",
  "Ipswich_Manchester City": "Sun 19 Jan 2025",
  "Chelsea_Wolves": "Mon 20 Jan 2025",
  "Liverpool_Ipswich": "Sat 25 Jan 2025",
  "Wolves_Arsenal": "Sat 25 Jan 2025",
  "Brighton_Everton": "Sat 25 Jan 2025",
  "Southampton_Newcastle": "Sat 25 Jan 2025",
  "Bournemouth_Nott'm Forest": "Sat 25 Jan 2025",
  "Manchester City_Chelsea": "Sat 25 Jan 2025",
  "Crystal Palace_Brentford": "Sun 26 Jan 2025",
  "Tottenham_Leicester": "Sun 26 Jan 2025",
  "Aston Villa_West Ham": "Sun 26 Jan 2025",
  "Fulham_Manchester United": "Sun 26 Jan 2025",
  "Nott'm Forest_Brighton": "Sat 1 Feb 2025",
  "Newcastle_Fulham": "Sat 1 Feb 2025",
  "Everton_Leicester": "Sat 1 Feb 2025",
  "Bournemouth_Liverpool": "Sat 1 Feb 2025",
  "Ipswich_Southampton": "Sat 1 Feb 2025",
  "Wolves_Aston Villa": "Sat 1 Feb 2025",
  "Manchester United_Crystal Palace": "Sun 2 Feb 2025",
  "Brentford_Tottenham": "Sun 2 Feb 2025",
  "Arsenal_Manchester City": "Sun 2 Feb 2025",
  "Chelsea_West Ham": "Mon 3 Feb 2025",
  "Everton_Liverpool": "Wed 12 Feb 2025",
  "Brighton_Chelsea": "Fri 14 Feb 2025",
  "Leicester_Arsenal": "Sat 15 Feb 2025",
  "Southampton_Bournemouth": "Sat 15 Feb 2025",
  "West Ham_Brentford": "Sat 15 Feb 2025",
  "Aston Villa_Ipswich": "Sat 15 Feb 2025",
  "Manchester City_Newcastle": "Sat 15 Feb 2025",
  "Fulham_Nott'm Forest": "Sat 15 Feb 2025",
  "Crystal Palace_Everton": "Sat 15 Feb 2025",
  "Liverpool_Wolves": "Sun 16 Feb 2025",
  "Tottenham_Manchester United": "Sun 16 Feb 2025",
  "Aston Villa_Liverpool": "Wed 19 Feb 2025",
  "Leicester_Brentford": "Fri 21 Feb 2025",
  "Everton_Manchester United": "Sat 22 Feb 2025",
  "Ipswich_Tottenham": "Sat 22 Feb 2025",
  "Fulham_Crystal Palace": "Sat 22 Feb 2025",
  "Arsenal_West Ham": "Sat 22 Feb 2025",
  "Bournemouth_Wolves": "Sat 22 Feb 2025",
  "Southampton_Brighton": "Sat 22 Feb 2025",
  "Aston Villa_Chelsea": "Sat 22 Feb 2025",
  "Newcastle_Nott'm Forest": "Sun 23 Feb 2025",
  "Manchester City_Liverpool": "Sun 23 Feb 2025",
  "Brighton_Bournemouth": "Tue 25 Feb 2025",
  "Crystal Palace_Aston Villa": "Tue 25 Feb 2025",
  "Wolves_Fulham": "Tue 25 Feb 2025",
  "Chelsea_Southampton": "Tue 25 Feb 2025",
  "Nott'm Forest_Arsenal": "Wed 26 Feb 2025",
  "Brentford_Everton": "Wed 26 Feb 2025",
  "Tottenham_Manchester City": "Wed 26 Feb 2025",
  "Manchester United_Ipswich": "Wed 26 Feb 2025",
  "Liverpool_Newcastle": "Wed 26 Feb 2025",
  "West Ham_Leicester": "Thu 27 Feb 2025",
  "Nott'm Forest_Manchester City": "Sat 8 Mar 2025",
  "Brighton_Fulham": "Sat 8 Mar 2025",
  "Crystal Palace_Ipswich": "Sat 8 Mar 2025",
  "Liverpool_Southampton": "Sat 8 Mar 2025",
  "Brentford_Aston Villa": "Sat 8 Mar 2025",
  "Wolves_Everton": "Sat 8 Mar 2025",
  "Tottenham_Bournemouth": "Sun 9 Mar 2025",
  "Chelsea_Leicester": "Sun 9 Mar 2025",
  "Manchester United_Arsenal": "Sun 9 Mar 2025",
  "West Ham_Newcastle": "Mon 10 Mar 2025",
  "Everton_West Ham": "Sat 15 Mar 2025",
  "Ipswich_Nott'm Forest": "Sat 15 Mar 2025",
  "Manchester City_Brighton": "Sat 15 Mar 2025",
  "Southampton_Wolves": "Sat 15 Mar 2025",
  "Bournemouth_Brentford": "Sat 15 Mar 2025",
  "Arsenal_Chelsea": "Sun 16 Mar 2025",
  "Fulham_Tottenham": "Sun 16 Mar 2025",
  "Leicester_Manchester United": "Sun 16 Mar 2025",
  "Arsenal_Fulham": "Tue 1 Apr 2025",
  "Wolves_West Ham": "Tue 1 Apr 2025",
  "Nott'm Forest_Manchester United": "Tue 1 Apr 2025",
  "Bournemouth_Ipswich": "Wed 2 Apr 2025",
  "Brighton_Aston Villa": "Wed 2 Apr 2025",
  "Manchester City_Leicester": "Wed 2 Apr 2025",
  "Newcastle_Brentford": "Wed 2 Apr 2025",
  "Southampton_Crystal Palace": "Wed 2 Apr 2025",
  "Liverpool_Everton": "Wed 2 Apr 2025",
  "Chelsea_Tottenham": "Thu 3 Apr 2025",
  "Everton_Arsenal": "Sat 5 Apr 2025",
  "Crystal Palace_Brighton": "Sat 5 Apr 2025",
  "Ipswich_Wolves": "Sat 5 Apr 2025",
  "West Ham_Bournemouth": "Sat 5 Apr 2025",
  "Aston Villa_Nott'm Forest": "Sat 5 Apr 2025",
  "Brentford_Chelsea": "Sun 6 Apr 2025",
  "Fulham_Liverpool": "Sun 6 Apr 2025",
  "Tottenham_Southampton": "Sun 6 Apr 2025",
  "Manchester United_Manchester City": "Sun 6 Apr 2025",
  "Leicester_Newcastle": "Mon 7 Apr 2025",
  "Manchester City_Crystal Palace": "Sat 12 Apr 2025",
  "Brighton_Leicester": "Sat 12 Apr 2025",
  "Nott'm Forest_Everton": "Sat 12 Apr 2025",
  "Southampton_Aston Villa": "Sat 12 Apr 2025",
  "Arsenal_Brentford": "Sat 12 Apr 2025",
  "Chelsea_Ipswich": "Sun 13 Apr 2025",
  "Liverpool_West Ham": "Sun 13 Apr 2025",
  "Wolves_Tottenham": "Sun 13 Apr 2025",
  "Newcastle_Manchester United": "Sun 13 Apr 2025",
  "Bournemouth_Fulham": "Mon 14 Apr 2025",
  "Newcastle_Crystal Palace": "Wed 16 Apr 2025",
  "Brentford_Brighton": "Sat 19 Apr 2025",
  "Crystal Palace_Bournemouth": "Sat 19 Apr 2025",
  "Everton_Manchester City": "Sat 19 Apr 2025",
  "West Ham_Southampton": "Sat 19 Apr 2025",
  "Aston Villa_Newcastle": "Sat 19 Apr 2025",
  "Fulham_Chelsea": "Sun 20 Apr 2025",
  "Ipswich_Arsenal": "Sun 20 Apr 2025",
  "Manchester United_Wolves": "Sun 20 Apr 2025",
  "Leicester_Liverpool": "Sun 20 Apr 2025",
  "Tottenham_Nott'm Forest": "Mon 21 Apr 2025",
  "Manchester City_Aston Villa": "Tue 22 Apr 2025",
  "Arsenal_Crystal Palace": "Wed 23 Apr 2025",
  "Chelsea_Everton": "Sat 26 Apr 2025",
  "Brighton_West Ham": "Sat 26 Apr 2025",
  "Newcastle_Ipswich": "Sat 26 Apr 2025",
  "Southampton_Fulham": "Sat 26 Apr 2025",
  "Wolves_Leicester": "Sat 26 Apr 2025",
  "Bournemouth_Manchester United": "Sun 27 Apr 2025",
  "Liverpool_Tottenham": "Sun 27 Apr 2025",
  "Nott'm Forest_Brentford": "Thu 1 May 2025",
  "Manchester City_Wolves": "Fri 2 May 2025",
  "Aston Villa_Fulham": "Sat 3 May 2025",
  "Everton_Ipswich": "Sat 3 May 2025",
  "Leicester_Southampton": "Sat 3 May 2025",
  "Arsenal_Bournemouth": "Sat 3 May 2025",
  "Brentford_Manchester United": "Sun 4 May 2025",
  "Brighton_Newcastle": "Sun 4 May 2025",
  "West Ham_Tottenham": "Sun 4 May 2025",
  "Chelsea_Liverpool": "Sun 4 May 2025",
  "Crystal Palace_Nott'm Forest": "Mon 5 May 2025",
  "Fulham_Everton": "Sat 10 May 2025",
  "Ipswich_Brentford": "Sat 10 May 2025",
  "Southampton_Manchester City": "Sat 10 May 2025",
  "Wolves_Brighton": "Sat 10 May 2025",
  "Bournemouth_Aston Villa": "Sat 10 May 2025",
  "Newcastle_Chelsea": "Sun 11 May 2025",
  "Manchester United_West Ham": "Sun 11 May 2025",
  "Nott'm Forest_Leicester": "Sun 11 May 2025",
  "Tottenham_Crystal Palace": "Sun 11 May 2025",
  "Liverpool_Arsenal": "Sun 11 May 2025",
  "Aston Villa_Tottenham": "Fri 16 May 2025",
  "Chelsea_Manchester United": "Fri 16 May 2025",
  "Everton_Southampton": "Sun 18 May 2025",
  "West Ham_Nott'm Forest": "Sun 18 May 2025",
  "Brentford_Fulham": "Sun 18 May 2025",
  "Leicester_Ipswich": "Sun 18 May 2025",
  "Arsenal_Newcastle": "Sun 18 May 2025",
  "Brighton_Liverpool": "Mon 19 May 2025",
  "Crystal Palace_Wolves": "Tue 20 May 2025",
  "Manchester City_Bournemouth": "Tue 20 May 2025",
  "Bournemouth_Leicester": "Sun 25 May 2025",
  "Fulham_Manchester City": "Sun 25 May 2025",
  "Ipswich_West Ham": "Sun 25 May 2025",
  "Liverpool_Crystal Palace": "Sun 25 May 2025",
  "Manchester United_Aston Villa": "Sun 25 May 2025",
  "Newcastle_Everton": "Sun 25 May 2025",
  "Nott'm Forest_Chelsea": "Sun 25 May 2025",
  "Southampton_Arsenal": "Sun 25 May 2025",
  "Tottenham_Brighton": "Sun 25 May 2025",
  "Wolves_Brentford": "Sun 25 May 2025",
};

export const MAX_GW = 38;
