const NATIONALITY_TO_ISO2: Record<string, string> = {
  english: 'gb',
  british: 'gb',
  scottish: 'gb',
  welsh: 'gb',
  irish: 'ie',
  american: 'us',
  canadian: 'ca',
  australian: 'au',
  newzealander: 'nz',

  french: 'fr',
  german: 'de',
  spanish: 'es',
  portuguese: 'pt',
  italian: 'it',
  dutch: 'nl',
  belgian: 'be',
  swedish: 'se',
  norwegian: 'no',
  danish: 'dk',
  finnish: 'fi',
  swiss: 'ch',
  austrian: 'at',
  polish: 'pl',
  czech: 'cz',
  slovak: 'sk',
  hungarian: 'hu',
  romanian: 'ro',
  bulgarian: 'bg',
  greek: 'gr',
  croatian: 'hr',
  serbian: 'rs',
  bosnian: 'ba',
  slovenian: 'si',
  albanian: 'al',
  macedonian: 'mk',
  montenegrin: 'me',
  kosovan: 'xk',
  ukrainian: 'ua',
  russian: 'ru',
  belarusian: 'by',
  turkish: 'tr',
  icelandic: 'is',
  luxembourgish: 'lu',
  maltese: 'mt',
  cypriot: 'cy',
  latvian: 'lv',
  lithuanian: 'lt',
  estonian: 'ee',
  georgian: 'ge',
  armenian: 'am',
  azerbaijani: 'az',

  egyptian: 'eg',
  nigerian: 'ng',
  ghanaian: 'gh',
  senegalese: 'sn',
  ivorian: 'ci',
  cameroonian: 'cm',
  moroccan: 'ma',
  algerian: 'dz',
  tunisian: 'tn',
  malian: 'ml',
  guinean: 'gn',
  congolese: 'cd',
  ethiopian: 'et',
  kenyan: 'ke',
  tanzanian: 'tz',
  ugandan: 'ug',
  zimbabwean: 'zw',
  zambian: 'zm',
  angolan: 'ao',
  mozambican: 'mz',
  south_african: 'za',
  southafrican: 'za',
  gabonese: 'ga',
  burkinabe: 'bf',
  beninese: 'bj',
  togolese: 'tg',
  libyan: 'ly',
  sudanese: 'sd',
  rwandan: 'rw',
  gambian: 'gm',
  capeverdean: 'cv',
  liberian: 'lr',
  sierreonean: 'sl',
  somalian: 'so',
  somali: 'so',
  djiboutian: 'dj',
  eritrean: 'er',
  namibian: 'na',
  botswanan: 'bw',
  swazi: 'sz',
  lesothan: 'ls',
  malagasy: 'mg',

  brazilian: 'br',
  argentinian: 'ar',
  argentine: 'ar',
  colombian: 'co',
  uruguayan: 'uy',
  chilean: 'cl',
  peruvian: 'pe',
  ecuadorian: 'ec',
  venezuelan: 've',
  paraguayan: 'py',
  bolivian: 'bo',
  mexican: 'mx',
  honduran: 'hn',
  costarican: 'cr',
  jamaican: 'jm',
  trinidadian: 'tt',
  haitian: 'ht',
  cuban: 'cu',
  panamanian: 'pa',

  japanese: 'jp',
  korean: 'kr',
  southkorean: 'kr',
  chinese: 'cn',
  iranian: 'ir',
  persian: 'ir',
  saudi: 'sa',
  saudiarabian: 'sa',
  emirati: 'ae',
  qatari: 'qa',
  kuwaiti: 'kw',
  omani: 'om',
  bahraini: 'bh',
  jordanian: 'jo',
  lebanese: 'lb',
  iraqi: 'iq',
  syrian: 'sy',
  yemeni: 'ye',
  indian: 'in',
  pakistani: 'pk',
  bangladeshi: 'bd',
  indonesian: 'id',
  thai: 'th',
  vietnamese: 'vn',
  philippine: 'ph',
  filipino: 'ph',
  malaysian: 'my',
  singaporean: 'sg',
  uzbek: 'uz',
  kazakhstani: 'kz',
  uzbekistani: 'uz',

  fijian: 'fj',
};

const COUNTRY_NAME_TO_ISO2: Record<string, string> = {
  'england': 'gb-eng', 'scotland': 'gb-sct', 'wales': 'gb-wls',
  'northern ireland': 'gb-nir', 'ireland': 'ie', 'republic of ireland': 'ie',
  'france': 'fr', 'germany': 'de', 'spain': 'es', 'portugal': 'pt',
  'italy': 'it', 'netherlands': 'nl', 'belgium': 'be', 'sweden': 'se',
  'norway': 'no', 'denmark': 'dk', 'finland': 'fi', 'switzerland': 'ch',
  'austria': 'at', 'poland': 'pl', 'czech republic': 'cz', 'czechia': 'cz',
  'slovakia': 'sk', 'hungary': 'hu', 'romania': 'ro', 'bulgaria': 'bg',
  'greece': 'gr', 'croatia': 'hr', 'serbia': 'rs', 'bosnia': 'ba',
  'bosnia-herzegovina': 'ba', 'slovenia': 'si', 'albania': 'al',
  'north macedonia': 'mk', 'montenegro': 'me', 'kosovo': 'xk',
  'ukraine': 'ua', 'russia': 'ru', 'turkey': 'tr', 'iceland': 'is',
  'luxembourg': 'lu', 'malta': 'mt', 'latvia': 'lv', 'lithuania': 'lt',
  'estonia': 'ee', 'georgia': 'ge', 'armenia': 'am', 'azerbaijan': 'az',
  'united states': 'us', 'usa': 'us', 'canada': 'ca', 'mexico': 'mx',
  'brazil': 'br', 'argentina': 'ar', 'colombia': 'co', 'uruguay': 'uy',
  'chile': 'cl', 'peru': 'pe', 'ecuador': 'ec', 'venezuela': 've',
  'paraguay': 'py', 'bolivia': 'bo', 'costa rica': 'cr', 'jamaica': 'jm',
  'trinidad and tobago': 'tt', 'honduras': 'hn', 'panama': 'pa',
  'egypt': 'eg', 'nigeria': 'ng', 'ghana': 'gh', 'senegal': 'sn',
  'ivory coast': 'ci', 'côte d\'ivoire': 'ci', 'cameroon': 'cm',
  'morocco': 'ma', 'algeria': 'dz', 'tunisia': 'tn', 'mali': 'ml',
  'guinea': 'gn', 'dr congo': 'cd', 'congo': 'cg', 'ethiopia': 'et',
  'kenya': 'ke', 'tanzania': 'tz', 'uganda': 'ug', 'zimbabwe': 'zw',
  'zambia': 'zm', 'angola': 'ao', 'mozambique': 'mz', 'south africa': 'za',
  'gabon': 'ga', 'burkina faso': 'bf', 'togo': 'tg', 'liberia': 'lr',
  'sierra leone': 'sl', 'gambia': 'gm', 'cape verde': 'cv',
  'japan': 'jp', 'south korea': 'kr', 'korea republic': 'kr',
  'china': 'cn', 'iran': 'ir', 'iraq': 'iq', 'saudi arabia': 'sa',
  'india': 'in', 'indonesia': 'id', 'thailand': 'th', 'uzbekistan': 'uz',
  'australia': 'au', 'new zealand': 'nz',
};

export function getFlagUrl(nation: string): string {
  if (!nation) return '';

  const fbrefMatch = nation.match(/^([a-z]{2})\s+[A-Z]{3}$/);
  if (fbrefMatch) {
    const iso2 = fbrefMatch[1];
    return `https://flagcdn.com/24x18/${iso2}.png`;
  }

  const key = nation.toLowerCase().trim();

  const fromName = COUNTRY_NAME_TO_ISO2[key];
  if (fromName) return `https://flagcdn.com/24x18/${fromName}.png`;

  const adjKey = key.replace(/[\s-]/g, '');
  const fromAdj = NATIONALITY_TO_ISO2[adjKey];
  if (fromAdj) return `https://flagcdn.com/24x18/${fromAdj}.png`;

  return '';
}

export function getFlagSrc(nationality: string): string {
  return getFlagUrl(nationality);
}

export function getFlagSrcByCode(iso2: string): string {
  return `https://flagcdn.com/24x18/${iso2.toLowerCase()}.png`;
}
